name: Georgia Rae Observatory
favicon: null
layout_spectrum: 0.48938
typography_spectrum: 0.72931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7878093076869845
  lightness: 0.5023304403293878
  saturation: 0.10087915253825486
  rhythmicContrast: 0.44456356507726014
purpose: []
